spring.application.name=planetpulse

spring.datasource.url=jdbc:mysql://localhost:3306/planetpulse
spring.datasource.username=root
spring.datasource.password=7457944152Samit


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



server.port=8080